name: aishi
title: null

@import"{{ site.theme }}";

.page-header{
color:#ffff;
background-color:#A067AB;
background-image:linear-gradient(120deg,#5073B8,#A067AB);
}

#background-color: #15191C
#theme: minima

#html { 
#  background: url(https://user-images.githubusercontent.com/67992204/103472771-72e87180-4d5f-11eb-91aa-40373655df44.png) no-repeat center center fixed; 
#  -webkit-background-size: cover;
#  -moz-background-size: cover;
#  -o-background-size: cover;
#  background-size: cover;
#}

#defaults:
#  - scope:
#      path: ""
#    values:
#      image: https://user-images.githubusercontent.com/67992204/103472771-72e87180-4d5f-11eb-91aa-40373655df44.png) no-repeat center center fixed

#background-image: url(https://user-images.githubusercontent.com/67992204/103472771-72e87180-4d5f-11eb-91aa-40373655df44.png)
#background-position: center
#background-repeat: no-repeat
#background-size: cover

